### ISSUE TITLE
Explain in readme how to push to the registry once you've deployed

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/serverless-registry#11]
Our getting started guide (https://github.com/cloudflare/serverless-registry/?tab=readme-ov-file#deployment) currently shows you how to deploy the Worker, but doesn't explain how to upload an image to the registry.

**Comment by BrammyS** [comment]
Can't figure out how to do this. So this would be very helpful :)

**Comment by muhajirdev** [comment]
In case anyone wondering

```
$ docker pull alpine
$ docker tag alpine your-worker.workers.dev/my-alpine-image
$ docker login your-worker.workers.dev
$ docker push your-worker.workers.dev/my-alpine-image

**Comment by BrammyS** [comment]
> In case anyone wondering
> 
> ```
> $ docker pull alpine
> $ docker tag alpine your-worker.workers.dev/my-alpine-image
> $ docker login your-worker.workers.dev
> $ docker push your-worker.workers.dev/my-alpine-image
> ```

Thank you! That helps me out a lot!
What about version tagging btw? Is that simply adding `:1.1.0` or something similar to the end like normal?

**Comment by gabivlj** [comment]
Done!
