### ISSUE TITLE
is it possible to mirror official docker registry?

### ISSUE THREAD

**Issue by Bisstocuz** [cloudflare/serverless-registry#33]
how to do?

**Comment by spencerswagger** [comment]
@Bisstocuz 
Try https://github.com/ciiiii/cloudflare-docker-proxy
Or my fork https://github.com/spencerswagger/cloudflare-docker-proxy
it works well with my own domain

**Comment by gabivlj** [comment]
If you want to also cache the target docker registry in R2 with serverless registry you can try this one out: https://github.com/cloudflare/serverless-registry/pull/7

If you have any more doubts please re-open the issue!

**Comment by Bisstocuz** [comment]
> If you want to also cache the target docker registry in R2 with serverless registry you can try this one out: #7
> 
> If you have any more doubts please re-open the issue!

I am not clear about how to use, and I wanna `docker pull` with anonymous permission.
Here is my `wrangler.toml`:
```toml
[env.production.vars]
REGISTRIES_JSON = "[{ \"registry\": \"https://index.docker.io/v2\" }]"
```

The `docker pull` error is:
```
Attempting next endpoint for pull after error: Head \"https://docker-io.prox...credentials
```
