### ISSUE TITLE
Migrate from existing registry

### ISSUE THREAD

**Issue by harryzcy** [cloudflare/serverless-registry#4]
Can we have a easy way to migrate from existing registry? i.e. Let worker to import from an registry, and triggered by some API, or maybe use the cron trigger
This repo looks promising and I would like to gradually migrate over

**Comment by gabivlj** [comment]
Hey @harryzcy, could you test the branch of #7 and see if you can configure your existing registry with it?

**Comment by gabivlj** [comment]
Hi @harryzcy, we've merged the changes. We will be closing this out and mark it as done. If there is anything else please let me know!
