### ISSUE TITLE
How to delete an image from the registry?

### ISSUE THREAD

**Issue by Strangersknowme** [cloudflare/serverless-registry#46]
Is it possible to delete images from the registry? 

I tried using `skopeo delete` to delete the tagged image from the registry but it only deleted the `manifests`, the `blobs` are still there even after the registry `manifest` has been deleted.

Is there any script to delete the `blobs` or are the `blobs` supposed to just stay there? ML apps' `blobs` can be in several GBs so I don't understand how keeping the blobs after deleting the `manifests` is a good idea! I saw this #[PR](https://github.com/cloudflare/serverless-registry/pull/29) but it hasn't been merged. If you do end up merging this pr, can you please give an example on how to use this endpoint to delete the layers?

**Comment by gabivlj** [comment]
Right now it's not possible to remove layers from the registry unless by building custom tooling, it's something we still need to look for a bit deeper. 
The biggest problem here is that the safest way to perform GC with stop the world lock is not possible without heavy changes. There is obviously other ways to go about GC but not without drawbacks. I will be looking into the PR as it's a very key feature for a registry, but we need to make sure it prevents as much as possible data-races and unexpected data-loss.

**Comment by gabivlj** [comment]
I took a look today and I think this will help you! There is some docs on how to use the garbage collector.
https://github.com/cloudflare/serverless-registry/pull/48

Please let me know if you face any issues.

**Comment by gabivlj** [comment]
I have merged the garbage collection PR. I will close. Please re-open if you encounter any issues!
