### ISSUE TITLE
Support for container layers >500MB 

### ISSUE THREAD

**Issue by Shakahs** [cloudflare/serverless-registry#71]
Cloudflare / R2 would be the best choice for hosting large (30GB+) AI/ML container images for serverless inference (RunPod, Modal, etc.), because R2 is fast (ECR is painfully slow), and 30GB container pulls will rapidly grow bandwidth bills. 
But a 500MB layer size limit is a significant handicap.  
The best solution I see is to implement the necessary multipart upload process via a container push feature in Cloudflare Wrangler.

**Comment by gabivlj** [comment]
Can you see if the following issue thread  https://github.com/cloudflare/serverless-registry/issues/42#issuecomment-2366997382 or https://github.com/cloudflare/serverless-registry/tree/main/push works for you?

**Comment by gabivlj** [comment]
I will be closing this down. Please re-open if any of the alternatives do not work for you!
