### ISSUE TITLE
Faster upload speed

### ISSUE THREAD

**Issue by ctrlok** [cloudflare/serverless-registry#79]
Hey! I'm starting to work with a serverless registry, and I am a little bit frustrated with the upload speed. I have images 100+ GB in size, and uploading them takes a few hours. 

Is it possible to upload OCI tar/oci folders directly to R2? Direct upload to R2 is much faster.

**Comment by ctrlok** [comment]
I found where the problem is. 

It tries to upload one large blog (c362e36 < 32gb) again and again and again. I tried both with ./push/index.ts and with regctl so I assume problem is somewhere in registry logic. 

https://github.com/user-attachments/assets/e00b5e64-e69f-484b-84b6-70707870a458

**Comment by ctrlok** [comment]
I fixed my issue by those steps:

1. rename blobs in OCI image from `blobs/sha256/<hash>` to `blobs/sha256:<hash>`
2. use `rclone` to copy blobs to r2 
3. rename blobs back to `blobs/sha256/<hash>` 
4. use regctl to upload an oci image — it will see that blobs already exist and will not try to reupload them 

```bash
find ./imagename/blobs/sha256 -type f -exec bash -c 'mv "$0" "${0%/*}:$(basename $0)"' {} \;
rclone --progress copy ./imagename//blobs <rclone-org>:<bucketname>/imagename/blobs --s3-upload-cutoff=100M --s3-chunk-size=100M
find ./imagename/blobs -type f -name 'sha256:*' -exec bash -c 'mv "$0" "${0/:/\/}"' {} \;
regctl image copy ocidir://imagename:tag <bucketname>/imagename:tag
```

**Comment by ctrlok** [comment]
It will be nice to exclude regctl somehow completely. I think it is possible to read manifest and update it — then we can form a folder structure available for upload.

**Comment by gabivlj** [comment]
This comment also has nice tips on how to deal with large uploads:
https://github.com/cloudflare/serverless-registry/issues/42#issuecomment-2366997382.
